services:
    db:
        image: postgres:13
        volumes:
            - ./db:/var/lib/postgresql/data/pgdata
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
        ports:
            - 5433:5432
        environment:
            - POSTGRES_USER=user
            - POSTGRES_DB=mydatabase
            - POSTGRES_PASSWORD=12345
            - PGDATA=/var/lib/postgresql/data/pgdata
    app:
        image: country-search-app
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 8080:8080
        environment:
            - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/mydatabase
            - SPRING_DATASOURCE_USERNAME=user
            - SPRING_DATASOURCE_PASSWORD=12345
            - SPRING_JPA_HIBERNATE_DDL_AUTO=update
        depends_on:
            - db